name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^4.15.4
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^7.1.0
  flutter_svg: ^2.2.0
  google_sign_in: ^7.0.0
  internet_connection_checker: ^3.0.1
  persistent_bottom_nav_bar: ^6.2.1
  persistent_bottom_nav_bar_v2: ^6.1.0
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/constants/
  filename: assets.dart

flutter:
  uses-material-design: true

  assets:
    - assets/images/
