// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKzHML7GwvF1iSIxT2LGiJCCY3Ugs5N_g',
    appId: '1:74113511385:web:39c1f8fc2c04321ad7b3c8',
    messagingSenderId: '74113511385',
    projectId: 'ecommerce-3a474',
    authDomain: 'ecommerce-3a474.firebaseapp.com',
    storageBucket: 'ecommerce-3a474.firebasestorage.app',
    measurementId: 'G-SQV3MREKHT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8hs5qd9lKDhU-F3s5OrKPFpw5Ft5e1lY',
    appId: '1:74113511385:android:bb28978461d357bdd7b3c8',
    messagingSenderId: '74113511385',
    projectId: 'ecommerce-3a474',
    storageBucket: 'ecommerce-3a474.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7CKtiCm9GTZDWOLKhz61nvxJQsx_eJww',
    appId: '1:74113511385:ios:489cc2fcb79ce410d7b3c8',
    messagingSenderId: '74113511385',
    projectId: 'ecommerce-3a474',
    storageBucket: 'ecommerce-3a474.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

}